spring:
  application:
    name: classroom-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

    username: postgres.xnerbjidhcatodcgjpqm
    password: Sqs4fmrnjifAR39G
    driverClassName: org.postgresql.Driver

    hikari:
      data-source-properties:
        ssl: true
        sslmode: require

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/