spring.application.name=user-service

spring.datasource.url=jdbc:mysql://localhost:3306/dea?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off

spring.sql.init.mode=never

server.port=8091

