spring:
  application:
    name: QA-Service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SUPABASE_URL:jdbc:postgresql://localhost:5432/qa_service}

    username: ${SUPABASE_USER:postgres}
    password: ${SUPABASE_PASS:postgres}
    driverClassName: org.postgresql.Driver

    hikari:
      data-source-properties:
        ssl: true
        sslmode: require

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8097